### ISSUE TITLE
[Interpreter] Store instruction doesn't work with float pointer

### ISSUE THREAD

**Issue by zzzDavid** [sampsyo/bril#148]
## Description

`store` instruction raises error when writing to a float pointer.

### Example

```
@main() {
  one: int = const 1;
  seed: float = const 109658.0;
  rng: ptr<float> = alloc one;
  store rng seed;
}
```

### Error message
```
../bril/bril-ts/build/brili.js:789
process.on('unhandledRejection', e => { throw e; });
                                        ^
store argument 1 must be a Pointer
```

**Comment by sampsyo** [comment]
Thanks!! The problem in the reference interpreter is here:
https://github.com/sampsyo/bril/blob/9fa84eb485b16129a35d5e45bab4ca02dad57d6f/bril-ts/brili.ts#L632-L645

That case for `store` doesn't need to be a switch; it should just use `getArgument` directly:
https://github.com/sampsyo/bril/blob/9fa84eb485b16129a35d5e45bab4ca02dad57d6f/bril-ts/brili.ts#L239

…and support any `target.type`.

**Comment by Pat-Lafon** [comment]
@sampsyo I believe this issue can be closed.

**Comment by sampsyo** [comment]
Indeed; thanks!
