### ISSUE TITLE
No "Operations" section in "Syntax" page

### ISSUE THREAD

**Issue by Izolius** [sampsyo/bril#208]
There is the following text in https://capra.cs.cornell.edu/bril/lang/syntax.html#instruction section:
> op, a string: the opcode that determines what the instruction does. (See the [Operations](https://capra.cs.cornell.edu/bril/lang/syntax.html#operations) section, below.)

But there is no "operations" section so the link leads to nowhere. And therefore there is no place where all operations are described.

**Comment by sampsyo** [comment]
See [the "Core" section](https://capra.cs.cornell.edu/bril/lang/core.html) and subsequent sections in that chapter for the opcodes.

**Comment by Izolius** [comment]
But the Core section doesn't contain "const" operator. Are there any other core operations missing in that Section?

**Comment by sampsyo** [comment]
The `"op": "const"` case of the syntax is covered in the next bit on that page, where we describe constants in particular:
https://capra.cs.cornell.edu/bril/lang/syntax.html#constant
