### ISSUE TITLE
Semantics of calling print on a pointer?

### ISSUE THREAD

**Issue by Pat-Lafon** [sampsyo/bril#230]
Consider:
```
@main {
  five: int = const 5;
  x: ptr<int> = alloc five;
  print x;
  free x;
}

```

Currently, `brili` outputs `[object Object]` and `brilirs` outputs `Pointer { base: 0, offset: 0 }`, essentially just spitting out their internal representations. Given that https://www.cs.cornell.edu/courses/cs6120/2019fa/blog/manually-managed-memory/ says that "the representation of data in memory is abstract", this seems like not great behavior.

I was wondering if this behavior should be further specified? One could of course just keep it implementation defined, it could be "bad program" for which a nice interpreter would return an error, or it could print out the contents of the array either just at that index or from there untill the end(Which a couple benchmarks have written implementations for so this is desirable behavior but requires a compliant implementation to know the bounds of the array).

**Comment by sampsyo** [comment]
Very good question. I had kind of been thinking lately that the right thing to do is to just classify this as an error… printing something "behind" the pointer is certainly possible, but it seems like it's a bit nicer on the implementation to just have programs dereference the pointer if that's what they really want.

I think a good argument against making it an error is that sometimes it could be useful for debugging. That is, being able to print the current (implementation-defined notion of the) value of the pointer might help narrow down a bug, and there's not really any other way to get a hint about "where" a given pointer currently is. So maybe classifying it as an error/UB, but allowing implementations to print stuff anyway is an acceptable tactic?

**Comment by Pat-Lafon** [comment]
You can get some of the debugging utility by calling `free` and forcing an error but it is less convenient since it ends the program.

**Comment by sampsyo** [comment]
I think the low-hanging fruit here is just to say that implementations can do whatever they want… it's not an error, but you're allowed to just print, like, `pointer` or something if you have nothing sensible to print. Does that sound reasonable?

**Comment by Pat-Lafon** [comment]
It's reasonable and doesn't require any changes which is nice. In an ideal world, I would just make it an error and use something like https://www.cs.cornell.edu/courses/cs6120/2019fa/blog/brildb/ if it had support beyond core Bril.

**Comment by sampsyo** [comment]
OK, sounds good! Added a note about implementation-definedness to the docs.
