### ISSUE TITLE
ts2bril error: boolean constant

### ISSUE THREAD

**Issue by gyauney** [sampsyo/bril#25]
`ts2bril` throws an error when it encounters a boolean constant instruction.

For example, the line `var x : boolean = true;` makes it throw the error: `unimplemented type boolean`. This occurs with or without the type annotation in the code.

**Comment by sampsyo** [comment]
Thanks!! The thing mapping TypeScript types to Bril types was being to strict in its checks. I fixed it by using bitwise & instead of strict equality and allowing TypeScript's literal types.
