### ISSUE TITLE
[Documentation] Missing installation instructions for ts2bril, brilck

### ISSUE THREAD

**Issue by vmakieienko** [sampsyo/bril#250]
Please mentione in doc that user must install ts2bril in order to run tests:

```
$ deno install ts2bril.ts --allow-all
$ deno install brilck.ts --allow-all
```

And probably fix existing instruction for brili:

```
$ deno install brili.ts --allow-all
```

Consider replacing `--allow-all` with more granular permissionns.

**Comment by sampsyo** [comment]
Hello! There are instructions in the docs for those tools:
https://capra.cs.cornell.edu/bril/tools/ts2bril.html
https://capra.cs.cornell.edu/bril/tools/brilck.html

You're right that we could indicate in the README that testing these tools requires them to be installed... or we could just change it to recommend only testing the basic tools?

Oddly, on my machine, Deno does not need any additional permissions for `brili.ts`.

**Comment by vmakieienko** [comment]
> Oddly, on my machine, Deno does not need any additional permissions for brili.ts

I am not sure about `brili.ts`, after discovering fix for `ts2bril` and `brilck`, just made an assumption.

>  or we could just change it to recommend only testing the basic tools?

How to only test the basic tools? I am trying to run `make test` since this Sunday. So far I got tests 1..105 - ok. AFAIK Turnt is the problem. Maybe I need to use a particular version of it?

**Comment by sampsyo** [comment]
You can run individual test suites by just referencing them on the command line. Something like:

```
turnt test/interp*/**/*.bril test/parse/*.bril test/print/*.json
```

…to just test the interpreter, parser, and pretty-printer.

**Comment by vmakieienko** [comment]
Thanks a lot.
