### ISSUE TITLE
 Suggestion to move `dot-product.bril` benchmark to `mem` directory

### ISSUE THREAD

**Issue by Lai-YT** [sampsyo/bril#328]
The benchmark program [dot-product.bril](https://github.com/sampsyo/bril/blob/main/benchmarks/core/dot-product.bril), which performs a dot product on two vectors using the memory extension of Bril, is currently placed in the `core` directory. Considering its reliance on the memory extension, it might be more appropriate to place this program under the `mem` directory instead of `core`.

> Thank you so much for the great CS 6120!!

**Comment by sampsyo** [comment]
Thanks!! Seems right to me—any chance you wouldn't mind opening a small PR to move the benchmark?

**Comment by Lai-YT** [comment]
Sure! I'll make a change on this. :ok_person:
