### ISSUE TITLE
LVN opportunity to fold "lt" and "gt"

### ISSUE THREAD

**Issue by nightdr** [sampsyo/bril#332]
In a similar vein to the equality operator constant folding, I believe that in the case of comparison operators "lt" and "gt", if both arguments have the same number, we can return false.

For example, in fold-comparisons.bril, I think we would be able to optimize no_fold4 and no_fold5 to false.

**Comment by sampsyo** [comment]
Hi! FWIW, the example optimizations in the `examples/` directory are not meant to be exhaustive in any sense; they are there to demonstrate a principle. So the point is about illustration, not catching every case. In this example optimization, we're showing constant folding, not the peephole optimization that involves self-comparison. Anyway, you're welcome to implement that in your own optimization pass!!

**Comment by nightdr** [comment]
Ah I see, thanks for the response and for open sourcing the course!
