### ISSUE TITLE
Error when install `brili` using `deno` "error: brili.ts was not found in either jsr or npm."

### ISSUE THREAD

**Issue by johnpzh** [sampsyo/bril#338]
Hi there. I was trying to install `brili` using `deno` but ran into an error. I am using macOS 13.7. I installed Deno according to their website (https://deno.com/), and I cloned `brili` repo locally. 

Under the repo root (btw, I am not sure if I am supposed to be under the repo root), I ran 
```bash
$ deno install brili.ts
```
It returned
```bash
error: brili.ts was not found in either jsr or npm.
```

I have searched a little bit but haven't found anything useful. I am not familiar with `deno`. I was wondering if I did something wrong. Thank you!

**Comment by sampsyo** [comment]
Yo! Would you mind including which version of Deno you have?

**Comment by johnpzh** [comment]
Hi! My Deno version is `2.0.0`. 

```bash
deno 2.0.0 (stable, release, aarch64-apple-darwin)
v8 12.9.202.13-rusty
typescript 5.6.2
```

**Comment by sampsyo** [comment]
Thanks! Looks like the `deno install` CLI changed in 2.0; it appears that we now want `deno install -g brili.ts`. I'll update the docs!
