### ISSUE TITLE
LVN should not crash on divide-by-zero

### ISSUE THREAD

**Issue by avanhatt** [sampsyo/bril#40]
The current implementation of constant folding via local value numbering in `lvn.py` crashes when the program divides by zero. Instead of crashing, the compiler should bail on folding constants when there are dynamic errors. 

Minimal example:
```
void main() {
entry:
  zero : int = const 0;
  one : int = const 1;
  baddiv : int = div one zero;
  print baddiv;
}
```

Stack trace:
```
Traceback (most recent call last):
  File "examples/lvn.py", line 243, in <module>
    lvn(bril, '-p' in sys.argv, '-c' in sys.argv, '-f' in sys.argv)
  File "examples/lvn.py", line 236, in lvn
    fold=_fold if fold else lambda n2c, v: None,
  File "examples/lvn.py", line 160, in lvn_block
    const = fold(num2const, val)
  File "examples/lvn.py", line 211, in _fold
    return FOLDABLE_OPS[value.op](*const_args)
  File "examples/lvn.py", line 197, in <lambda>
    'div': lambda a, b: a // b,
ZeroDivisionError: integer division or modulo by zero
```

**Comment by sampsyo** [comment]
Good catch. If we had such an instruction, we could emit, like, `raise DivByZero` when we know that something is guaranteed to do that. As it stands, you're right, we should just stop trying to constant-fold and leave the division in place.

**Comment by avanhatt** [comment]
Will submit a PR shortly!
