### ISSUE TITLE
Sieve appears to have an invalid ptr type!

### ISSUE THREAD

**Issue by priyasrikumar** [sampsyo/bril#87]
Hi, 

It looks like on [line 27 of `sieve.bril` ](https://github.com/sampsyo/bril/blob/master/benchmarks/sieve.bril#L27) there is a reference to a `ptr<book>`... not sure that this is valid Bril!

**Comment by sampsyo** [comment]
🤣 Nope! Perhaps @tedbauer can confirm, but I assume it's supposed to be `ptr<bool>`. 📖
